# Generated by Django 2.1.7 on 2019-03-25 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('idAnnonce', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('commentaites', models.CharField(max_length=255)),
                ('idUser', models.ForeignKey(on_delete='DO_NOTHING', related_name='proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('codeCouleur', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nomCouleur', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('nomFabricant', models.CharField(max_length=255)),
                ('idFabricant', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idMarque', models.AutoField(primary_key=True, serialize=False)),
                ('nomMarque', models.CharField(max_length=50)),
                ('imageMarque', models.ImageField(upload_to='marque/images/')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('idModele', models.AutoField(primary_key=True, serialize=False)),
                ('codeModele', models.CharField(max_length=10)),
                ('nomModele', models.CharField(max_length=255)),
                ('couleurCompatible', models.ManyToManyField(blank=True, related_name='modeles', to='SayaraApi.Couleur')),
                ('marqueModele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='SayaraApi.Marque')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomOption', models.CharField(max_length=255)),
                ('codeOption', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fabricant', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('Fabricant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricant', to='SayaraApi.Fabricant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('numChassis', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
                ('imageVehicle', models.ImageField(default='images/vehicules/voiture.jpg', upload_to='images/vehicules')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False)),
                ('nomVersion', models.CharField(max_length=100)),
                ('codeVersion', models.CharField(max_length=20)),
                ('modeleVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='SayaraApi.Modele')),
                ('optionsVersion', models.ManyToManyField(blank=True, related_name='versions', to='SayaraApi.Option')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='versionVoiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='SayaraApi.Version'),
        ),
        migrations.AddField(
            model_name='fabricant',
            name='marqueFabricant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricants', to='SayaraApi.Marque'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='idVehicule',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='vehicule', to='SayaraApi.Vehicule'),
        ),
    ]
