# Generated by Django 2.1.7 on 2019-03-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idMarque', models.IntegerField(primary_key=True, serialize=False)),
                ('nomMarque', models.CharField(max_length=50)),
                ('imageMarque', models.ImageField(upload_to='marque/images/')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('nomModele', models.CharField(max_length=255)),
                ('idModele', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marqueModele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='SayaraApi.Marque')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('numChassis', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponible', models.BooleanField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('nomVersion', models.CharField(max_length=100)),
                ('codeVersion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modeleVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='SayaraApi.Modele')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='versionVoiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='SayaraApi.Version'),
        ),
    ]
