# Generated by Django 2.1.7 on 2019-09-15 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
