# Generated by Django 2.1.7 on 2019-03-24 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SayaraApi', '0002_utilisateurfabricant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('codeCouleur', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fabricant', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('Fabricant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricant', to='SayaraApi.Fabricant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilisateurfabricant',
            name='Fabricant',
        ),
        migrations.RemoveField(
            model_name='utilisateurfabricant',
            name='user',
        ),
        migrations.DeleteModel(
            name='UtilisateurFabricant',
        ),
        migrations.AddField(
            model_name='modele',
            name='couleurCompatible',
            field=models.ManyToManyField(related_name='modeles', to='SayaraApi.Couleur'),
        ),
    ]
