# Generated by Django 2.1.7 on 2019-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0002_auto_20190302_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='imageMarque',
            field=models.ImageField(upload_to='images/marques'),
        ),
    ]
