# Generated by Django 2.1.7 on 2019-03-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0003_auto_20190324_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couleur',
            old_name='nom',
            new_name='nomCouleur',
        ),
    ]
