# Generated by Django 2.1.7 on 2019-09-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0003_auto_20190915_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SayaraApi.VehiculeNeuf'),
        ),
    ]
