# Generated by Django 2.1.7 on 2019-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0003_auto_20190302_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='imageMarque',
            field=models.ImageField(upload_to='media/images/marques'),
        ),
    ]
