# Generated by Django 2.1.7 on 2019-03-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0004_auto_20190302_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='imageMarque',
            field=models.ImageField(upload_to='images/marques'),
        ),
        migrations.AlterField(
            model_name='modele',
            name='idModele',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
