# Generated by Django 2.1.7 on 2019-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SayaraApi', '0005_auto_20190302_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='imageVehicle',
            field=models.ImageField(default='images/vehicules/voiture.jpg', upload_to='images/vehicules'),
        ),
    ]
